import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import "./style.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Toast, { useToast } from 'vue-toastification';
import 'vue-toastification/dist/index.css';
import AOS from "aos";
import "aos/dist/aos.css";
const app = createApp(App);
app.use(router);
app.use(Toast);
app.use(createPinia());
app.mount("#app");
AOS.init();
